# Generated by Django 5.1.1 on 2024-10-07 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedEmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('received_date_time', models.DateTimeField()),
                ('subject', models.CharField(max_length=255)),
                ('has_attachments', models.BooleanField()),
                ('body_content_type', models.CharField(max_length=50)),
                ('body_content', models.TextField()),
                ('body_preview', models.TextField()),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_address', models.EmailField(max_length=254)),
                ('from_name', models.CharField(max_length=255)),
                ('from_address', models.EmailField(max_length=254)),
                ('to_recipients', models.JSONField()),
                ('cc_recipients', models.JSONField()),
                ('jiraissueid', models.CharField(max_length=255, null=True)),
                ('is_ticket_trigger', models.BooleanField(default=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_emails', to='manage.mailbox')),
            ],
        ),
    ]
